# Generated by Django 3.0 on 2019-12-19 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ban',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键自增')),
                ('title', models.CharField(max_length=64, verbose_name='标题，病名')),
                ('content', models.CharField(max_length=2048, verbose_name='内容，标签内容')),
            ],
        ),
        migrations.CreateModel(
            name='sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键自增')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('content', models.CharField(max_length=2048, verbose_name='文章渲染后的内容')),
                ('pub_user', models.IntegerField(verbose_name='发表人id')),
                ('pub_time', models.DateTimeField(verbose_name='发布时间')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击量')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键id，自增')),
                ('email', models.CharField(max_length=32, unique=True, verbose_name='邮箱、账号')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='密码，暂时不加密')),
                ('is_doctor', models.IntegerField(default=1, verbose_name='是否专家，0是，1否')),
                ('last_login', models.DateTimeField(verbose_name='最后登录时间')),
                ('token', models.CharField(max_length=44, null=True, verbose_name='token')),
                ('vercode', models.CharField(max_length=4, null=True, verbose_name='验证码')),
            ],
        ),
    ]
