# Generated by Django 3.0 on 2019-12-19 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhelpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(null=True, verbose_name='最后登录时间'),
        ),
    ]
